import os
import json
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI


# ============================================================
# ENVIRONMENT
# ============================================================

load_dotenv(override=True)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

if not OPENAI_API_KEY:
    raise RuntimeError(
        "OPENAI_API_KEY environment variable was not found."
    )
client = OpenAI(api_key=OPENAI_API_KEY)


# ============================================================
# PROJECT PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

EVIDENCE_FILE = BASE_DIR / "portfolio_evidence.json"
NARRATIVE_FILE = BASE_DIR / "portfolio_narrative.json"


# ============================================================
# LOAD JSON HELPER
# ============================================================

def load_json_file(path):
    """
    Load a JSON file and return its contents.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"{path.name} was not found at {path}"
        )

    try:
        with open(
            path,
            "r",
            encoding="utf-8"
        ) as file:

            return json.load(file)

    except json.JSONDecodeError as error:
        raise RuntimeError(
            f"{path.name} contains invalid JSON: {error}"
        )

    except Exception as error:
        raise RuntimeError(
            f"Could not read {path.name}: {error}"
        )


# ============================================================
# LOAD PORTFOLIO EVIDENCE
# ============================================================

def load_data():
    """
    Load the evidence and narrative generated by
    portfolio_analyzer_v6.py / generate_narrative().
    """

    evidence = load_json_file(EVIDENCE_FILE)

    # Narrative is optional. It may not have been generated yet
    # (e.g. generate_narrative() failed or hasn't run).
    if NARRATIVE_FILE.exists():
        narrative = load_json_file(NARRATIVE_FILE)
    else:
        narrative = {
            "narrative": {
                "overall_assessment":
                    "No generated portfolio narrative is available."
            }
        }

    return evidence, narrative


# ============================================================
# ANSWER CUSTOMER QUESTION
# ============================================================

def answer_customer_question(
    question,
    evidence=None,
    narrative=None
):
    """
    Answer a customer question using only the supplied
    portfolio evidence and narrative.

    If evidence/narrative are not supplied, they are loaded
    automatically from the generated JSON files.
    """

    # --------------------------------------------------------
    # LOAD DATA IF NOT PROVIDED
    # --------------------------------------------------------

    if evidence is None or narrative is None:
        evidence, narrative = load_data()

    # --------------------------------------------------------
    # VALIDATE QUESTION
    # --------------------------------------------------------

    if not question or not str(question).strip():
        raise ValueError(
            "Customer question cannot be empty."
        )

    # --------------------------------------------------------
    # SYSTEM PROMPT
    # --------------------------------------------------------

    system_prompt = """
You are a customer-facing AI portfolio analysis assistant.

Your job is to answer questions about the customer's portfolio
using ONLY the supplied portfolio evidence and generated
portfolio narrative.

============================================================
GROUNDING RULES
============================================================

1. NEVER invent portfolio facts, numbers, news, causes,
   holdings, prices, returns, or dates.

2. Use exact numbers from the supplied evidence whenever
   they are available.

3. Clearly distinguish between:

   - observed market movement
   - retrieved news
   - possible explanation
   - proven causation

4. News sentiment does NOT automatically mean the news caused
   a stock price movement.

5. If the evidence does not answer the customer's question,
   explicitly say that the available evidence is insufficient.

6. Do not invent explanations for unexplained stock movements.

7. Do not provide personalized investment advice.

8. Do not tell the customer to buy, sell, or hold a security.

9. If the customer asks whether they should buy, sell, or hold
   a security:

   - do NOT make a recommendation
   - summarize the relevant evidence
   - clearly state that the evidence does not constitute
     personalized investment advice

10. Never use causal language such as:

    "caused"
    "drove"
    "resulted in"
    "led to"
    "was responsible for"
    "likely contributed"

    unless the supplied evidence explicitly establishes
    causation.

11. Prefer cautious language such as:

    "aligned with"
    "consistent with"
    "possible explanation"
    "the available news indicates"
    "the evidence shows"

12. Do not predict future prices or returns unless explicit
    forecast data is supplied.

13. If mentioning a stock, include its ticker.

14. If a stock has no relevant news evidence, say so rather
    than inventing an explanation.

15. If the question asks about the entire portfolio, use the
    portfolio-level evidence where available rather than
    focusing on a single holding.

16. If the question asks about sectors, use the supplied
    sector evidence.

17. If the question asks about the biggest gainers or losers,
    use the supplied contributor data.

18. Do not claim that news explains a price movement merely
    because the article and price movement happened around
    the same time.

19. Keep answers concise and easy for a customer to understand.

20. Answer naturally in plain English.
"""

    # --------------------------------------------------------
    # USER PROMPT
    # --------------------------------------------------------

    user_prompt = f"""
CUSTOMER QUESTION:

{question}

============================================================
PORTFOLIO EVIDENCE
============================================================

{json.dumps(
    evidence,
    indent=2,
    ensure_ascii=False
)}

============================================================
GENERATED PORTFOLIO NARRATIVE
============================================================

{json.dumps(
    narrative,
    indent=2,
    ensure_ascii=False
)}

============================================================
INSTRUCTIONS
============================================================

Answer the customer's question using ONLY the supplied
portfolio evidence and narrative.

If the supplied evidence is insufficient, say so clearly.

Do not invent missing information.
"""

    # --------------------------------------------------------
    # OPENAI REQUEST
    # --------------------------------------------------------

    try:

        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            temperature=0.2,
            messages=[
                {
                    "role": "system",
                    "content": system_prompt,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                },
            ],
        )

    except Exception as error:
        raise RuntimeError(
            f"OpenAI request failed: {error}"
        )

    # --------------------------------------------------------
    # GET ANSWER
    # --------------------------------------------------------

    answer = response.choices[0].message.content

    if not answer:
        raise RuntimeError(
            "OpenAI returned an empty response."
        )

    return answer.strip()


# ============================================================
# GENERATE PORTFOLIO NARRATIVE
# ============================================================

def generate_narrative(evidence=None):
    """
    Generate a short, grounded overall-assessment narrative for
    the portfolio, based ONLY on the supplied evidence (typically
    portfolio_evidence.json from portfolio_analyzer_v6.py).

    Saves the result to portfolio_narrative.json and returns it
    in the same shape the frontend/chat expect:

        {"narrative": {"overall_assessment": "..."}}

    This follows the same grounding rules as
    answer_customer_question: no invented facts, no causal
    language unless the evidence supports it, no investment
    advice.
    """

    if evidence is None:
        evidence = load_json_file(EVIDENCE_FILE)

    # --------------------------------------------------------
    # SYSTEM PROMPT
    # --------------------------------------------------------

    system_prompt = """
You are a customer-facing AI portfolio analysis assistant.

Write a short overall assessment of the customer's portfolio
for today, using ONLY the supplied portfolio evidence.

============================================================
GROUNDING RULES
============================================================

1. NEVER invent portfolio facts, numbers, news, causes,
   holdings, prices, returns, or dates.

2. Use exact numbers from the supplied evidence whenever
   they are available.

3. Clearly distinguish between observed market movement and
   any news-based explanation for it.

4. News sentiment does NOT automatically mean the news caused
   a stock price movement.

5. Do not invent explanations for unexplained stock movements.
   If a holding moved but no relevant news was found, say so
   plainly instead of guessing.

6. Do not provide personalized investment advice, and do not
   tell the customer to buy, sell, or hold any security.

7. Never use causal language such as "caused", "drove",
   "resulted in", "led to", "was responsible for" unless the
   evidence explicitly establishes causation. Prefer "aligned
   with", "consistent with", "a possible explanation".

8. If mentioning a stock, include its ticker.

9. Cover, briefly: the overall portfolio move, the sectors or
   holdings that mattered most today, and whether news evidence
   was found to help explain the biggest movers.

10. Keep it to 3-5 sentences, in plain English, no bullet points,
    no headers, no markdown formatting.
"""

    # --------------------------------------------------------
    # USER PROMPT
    # --------------------------------------------------------

    user_prompt = f"""
PORTFOLIO EVIDENCE:

{json.dumps(evidence, indent=2, ensure_ascii=False)}

============================================================
INSTRUCTIONS
============================================================

Write the overall assessment now, following the grounding
rules exactly. Return plain text only -- no JSON, no markdown,
no headers.
"""

    # --------------------------------------------------------
    # OPENAI REQUEST
    # --------------------------------------------------------

    try:

        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            temperature=0.2,
            messages=[
                {
                    "role": "system",
                    "content": system_prompt,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                },
            ],
        )

    except Exception as error:
        raise RuntimeError(
            f"OpenAI request failed: {error}"
        )

    # --------------------------------------------------------
    # GET NARRATIVE TEXT
    # --------------------------------------------------------

    text = response.choices[0].message.content

    if not text or not text.strip():
        raise RuntimeError(
            "OpenAI returned an empty narrative."
        )

    narrative = {
        "narrative": {
            "overall_assessment": text.strip()
        }
    }

    # --------------------------------------------------------
    # SAVE NARRATIVE
    # --------------------------------------------------------

    with open(
        NARRATIVE_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            narrative,
            file,
            indent=4,
            ensure_ascii=False
        )

    return narrative


# ============================================================
# CUSTOMER CHAT CLI
# ============================================================

def main():

    print()
    print("=" * 70)
    print("AI PORTFOLIO CUSTOMER ASSISTANT")
    print("=" * 70)

    try:
        evidence, narrative = load_data()

    except Exception as error:
        print()
        print("Could not load portfolio data.")
        print(error)
        return

    print()
    print("Portfolio evidence loaded.")
    print("Ask a question about the portfolio.")
    print("Type 'exit' to quit.")

    while True:

        print()
        question = input("Customer: ").strip()

        if question.lower() in ["exit", "quit"]:
            print("Goodbye.")
            break

        if not question:
            continue

        print()
        print("AI Assistant:")
        print("-" * 70)

        try:

            answer = answer_customer_question(
                question,
                evidence,
                narrative
            )

            print(answer)

        except Exception as error:

            print()
            print("Unable to answer the question.")
            print(error)


# ============================================================
# RUN DIRECTLY
# ============================================================

if __name__ == "__main__":
    main()